# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 7cdebb3b9798d2e4d630688dbcee6a48d9aa80bb28ed0bd8b616529a49ae71643c418eedb42ef7ffd8708f07772bd6b1e4abb2bb6e5ea2b6f9ad476e44118d52

test:
  domain_name: example.com 
  secret_key_base: e372821797692c2dc7500fa91994508f0d325804656b009db38b2fbb5ae5152cd7147585fa0efde562d0cfac71de9d8f09e9c9bf024a6ca6c94721a295cf42be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
